%*******************************************************************************
% Purpose:  Executes the PSO algorithm
%
% Outputs:  - This script add some information to the global gpso2d_results
%             structure, mainly populated by gpso2d_Cost.m function:
%             - gpso2d_results.filename: Path of the file where the structure is
%                                        contained
%             - gpso2d_results.inv_res.dispersion: Column vector containing the
%                              median dispersio of each iteration
%             - gpso2d_results.inv_res.rel_misfit_best: Column vector containing
%                              the relative misfit, in percentage, for the best
%                              model of each iteration (containing the regional
%                              trend, if it was estimated in the inversion)
%             - gpso2d_results.model: 'model' struct for the PSO execution
%             - gpso2d_results.data: 'data' struct for the PSO execution
%             - gpso2d_results.options: 'options' struct for the PSO execution
%             - gpso2d_results.opfun: 'opfun' struct for the PSO execution
%             - gpso2d_results.original_pso: matriz of swarm_size x iterations
%                              rows containing the original PSO generated models
%                              (the first columns contain the subsoil and then
%                              come the regional trend parameters, if exist)
%           - The gpso2d_results is exported as a *.mat file (version 7)
%
% History:  25-07-2018: Function creation
%                       José Luis García Pallero, jgpallero@gmail.com
%           01-07-2023: Add 32 bits save data
%                       José Luis García Pallero, jgpallero@gmail.com
%           24-03-2025: Change name from grav2d_ to gpso2d_
%                       Muhammet Ali Aygun, hgm003@hotmail.com
%*******************************************************************************
%Clear previous global variable
clear('gpso2d_results');
%Global variable to store results
global gpso2d_results;
%Identifier of new inversion, because this script calls pso_family(), which
%calls gpso2d_Cost, where gpso2d_results is employed
gpso2d_results.extra.new_inversion = 1;
%Identifier for filtering in the first iteration: 0/1 -> no filter/filter
gpso2d_results.extra.filt_first_it = 0;
gpso2d_results.extra.filt_first_it_o = gpso2d_results.extra.filt_first_it;
%Add the PSO software input and output structures
gpso2d_results.model = model;
gpso2d_results.data = data;
gpso2d_results.options = options;
gpso2d_results.opfun = opfun;
%PSO EXECUTION
tic;
results = pso_family(@gpso2d_Cost,model,data,options,opfun);
fprintf('PSO execution time: %.1f s\n',toc);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Check if results must be stores in 32 bits
if gpso2d_results.opfun.file_precision==32
    %Convert data to single
    results.historia = single(results.historia);
    gpso2d_results.inv_res.model = single(gpso2d_results.inv_res.model);
    gpso2d_results.inv_res.trend = single(gpso2d_results.inv_res.trend);
    gpso2d_results.inv_res.obs = single(gpso2d_results.inv_res.obs);
    gpso2d_results.inv_res.obs_trend = single(gpso2d_results.inv_res.obs_trend);
end
%Add the best models misfit
gpso2d_results.inv_res.rel_misfit_best = results.error_iter';
%Add the median dispersion to the structure
gpso2d_results.inv_res.dispersion = results.stat.distmed;
%Add the original models generated by PSO
gpso2d_results.inv_res.original_pso = results.historia;
%Filename
gpso2d_results.filename = [data.output.folder,filesep,data.output.prefix,...
                           'gpso2d_results.mat'];
%Export the structure to a file
fprintf(2,'Saving results to a file\n');
save(gpso2d_results.filename,'gpso2d_results','-v7');
fprintf(2,'Done!\n');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Author: Muhammet Ali Aygun
%
%Redistribution and use in source and binary forms, with or without
%modification, are permitted provided that the following conditions are met:
%
%- Redistributions of source code must retain the above copyright notice, this
%  list of conditions and the following disclaimer.
%- Redistributions in binary form must reproduce the above copyright notice,
%  this list of conditions and the following disclaimer in the documentation
%  and/or other materials provided with the distribution.
%- Neither the name of the copyright holders nor the names of its contributors
%  may be used to endorse or promote products derived from this software without
%  specific prior written permission.
%
%THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
%ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
%WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
%DISCLAIMED. 
