%*******************************************************************************
% Function: grav = gpso2d_GravityModels(rect,models,rho,points)
%
% Purpose:  Computes the gravity for a set of models generated by PSO
%
% Inputs:   - rect: Three-column matrix containing the geometric definition of
%                   the involved rectangles (in SI units):
%                   - Col. 1: Minimum X coordinate
%                   - Col. 2: Maximum X coordinate
%                   - Col. 3: Maximum Z coordinate, i.e., Z coordinate of the
%                             rectangle's top side
%           - models: Matrix with a number of columns equal to the number of
%                     rows or the argument 'rect'. Each column is the minimum Z
%                     coordinate (Z coordinate of the rectangle's bottom side)
%                     of the rectangle for the corresponding row in 'rect'. Each
%                     row is a different model.
%           - rho: Cell array of the same length as the rows of 'rect'
%                  containing in each element the density configuration for the
%                  corresponding rectangle. Each element is a two-column matrix,
%                  whose columns are:
%                  - Col. 1: Absolute height
%                  - Col. 2: Density from this height upwards
%           - points: Two-column matrix containing the attracted points
%                     coordinates:
%                     - Col. 1: X coordinate
%                     - Col. 2: Z coordinate
%                     All points must be outside all prisms
%
% Outputs:  - grav: Matrix of number of rows equal to number of points and
%                   number of columns equal to number of models with the
%                   attraction over each point by each model
%
% Note: This function does not perform any check about the input arguments
%
% History:  03-07-2023: Function creation
%                       José Luis García Pallero, jgpallero@gmail.com
%           03-03-2023: Change name from grav2d_ to gpso2d_
%                       José Luis García Pallero, jgpallero@gmail.com
%*******************************************************************************

function [grav] = gpso2d_GravityModels(rect,models,rho,points)

%Number of rectangles, models, and points
nr = size(rect,1);
nm = size(models,1);
np = size(points,1);
%Computed gravities
grav = zeros(np,nm);
%Check if we are working with constant density
crho = 1;
rho_val = zeros(nr,1);
for i=1:nr
    %Check if a definition is not for constant density
    if size(rho{i},1)~=1
        crho = 0;
        break;
    end
    %Add density value in case of constant density
    rho_val(i) = rho{i}(1,2);
end
%Checl if we are working with constant or variable density
if crho
    %Rectangles' definition
    rect_calc = [rect(:,1:2) zeros(nr,1) rect(:,3)];
    %Loop over all models
    for i=1:nm
        %Matrix of rectangles
        rect_calc(:,3) = models(i,:)';
        %Gravity computation
        grav(:,i) = gpso2d_GravityRectangle(rect_calc,rho_val,points);
    end
else
    %Loop over all models
    for i=1:nm
        %Rectangles' definition and densities
        rect_calc = [];
        rho_val = [];
        %Loop over all rectangles
        for j=1:nr
            %Auxiliary variables
            rc_aux = [];
            rv_aux = [];
            %Row in rc_aux matrix
            rrc = 0;
            %Check if its density is constant or variable
            if size(rho{j},1)==1
                %Add rectangle and density definition
                rc_aux = [rc_aux;[rect(j,1:2) models(i,j) rect(j,3)]];
                rv_aux = [rv_aux;rho{j}(1,2)];
                %Rows count increment is not needed here
            else
                %Is heigth of the model <= heigth of the density definitions?
                pos = models(i,j)<=rho{j}(:,1);
                %Is the model shallower than the shallowest density point?
                if sum(pos)==0
                    %Rectangle and density configurations
                    rc_aux = [rc_aux;[rect(j,1:2) models(i,j) rect(j,3)]];
                    rv_aux = [rv_aux;rho{j}(1,2)];
                else
                    %Loop over the density definition
                    for k=1:size(rho{j},1)
                        %Check if the model is below the definition
                        if pos(k)
                            %Add the subrectangle
                            if k==1
                                %The first rectangle has top height the surface
                                rc_aux = [rc_aux;...
                                          [rect(j,1:2) rho{j}(k,1) rect(j,3)]];
                                %Rows count increment
                                rrc = rrc+1;
                            else
                                %The other rectangles have as top height the
                                %bottom height of the precedent rectangle
                                rc_aux = [rc_aux;...
                                       [rect(j,1:2) rho{j}(k,1) rc_aux(rrc,3)]];
                                %Rows count increment
                                rrc = rrc+1;
                            end
                            %Add density value
                            rv_aux = [rv_aux;rho{j}(k,2)];
                        end
                    end
                    %Check if the model is deeper
                    if models(i,j)<rc_aux(end,3)
                        %Last subrectangle
                        rc_aux = [rc_aux;...
                                  [rect(j,1:2) models(i,j) rc_aux(rrc,3)]];
                        %Last density value
                        rv_aux = [rv_aux;rho{j}(end,2)];
                        %Rows count increment is not needed here
                    end
                end
            end
            %Update the rectangles and density matrices
            rect_calc = [rect_calc;rc_aux];
            rho_val = [rho_val;rv_aux];
        end
        %Gravity computation
        grav(:,i) = gpso2d_GravityRectangle(rect_calc,rho_val,points);
    end
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Copyright (c) 2023-2025, J.L.G. Pallero, jgpallero@gmail.com,
%                         J.L. Fernández Martínez, jlfm@uniovi.es
%                         Z. Fernández Muñiz, zulima@uniovi.es
%                         Sylvain Bonvalot, sylvain.bonvalot@ird.fr
%
%All rights reserved.
%
%Redistribution and use in source and binary forms, with or without
%modification, are permitted provided that the following conditions are met:
%
%- Redistributions of source code must retain the above copyright notice, this
%  list of conditions and the following disclaimer.
%- Redistributions in binary form must reproduce the above copyright notice,
%  this list of conditions and the following disclaimer in the documentation
%  and/or other materials provided with the distribution.
%- Neither the name of the copyright holders nor the names of its contributors
%  may be used to endorse or promote products derived from this software without
%  specific prior written permission.
%
%THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
%ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
%WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
%DISCLAIMED. IN NO EVENT SHALL COPYRIGHT HOLDER BE LIABLE FOR ANY DIRECT,
%INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
%BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
%DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
%LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
%OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
%ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
