/* Computes the gravity for a set of models generated by PSO over a set of
 * exterior points. This function is called internally by gpso2d_Cost.m */
#include<mex.h>
#include<stdio.h>
#include"GravityRectangle.c"
/*Macro for extracting element from a matrix stored in column major order*/
#define PCMO(totalRows,row,col) ((col)*(totalRows)+(row))
/*Function code*/
void mexFunction(int nlhs,mxArray* plhs[],int nrhs,const mxArray* prhs[])
{
    /*Inputs and their dimensions*/
    double* rect=NULL;
    double* models=NULL;
    double* points=NULL;
    mxArray* rho=NULL;
    double* rhod=NULL;
    int nr=0,nm=0,np=0,nmsr=0;
    /*Output*/
    double* grav=NULL;
    /*Auxiliary variables*/
    int i=0,j=0,k=0,l=0,n=0,pos=0;
    double h=0.0;
    double* rhoc=NULL;
    /*////////////////////////////////////////////////////////////////////////*/
    /*////////////////////////////////////////////////////////////////////////*/
    /*Rectangles geometry*/
    rect = mxGetPr(prhs[0]);
    nr = mxGetM(prhs[0]);
    /*Models (i.e., rectangles' bottom heights*/
    models = mxGetPr(prhs[1]);
    nm = mxGetM(prhs[1]);
    /*Points coordinates*/
    points = mxGetPr(prhs[3]);
    np = mxGetM(prhs[3]);
    /*Maximum number of subrectangles*/
    for(i=0;i<nr;i++)
    {
        /*Pointer to the element of the cell array*/
        rho = mxGetCell(prhs[2],i);
        /*Number of rows of the cell element*/
        n = mxGetM(rho);
        /*Check for the maximum value*/
        if(n>nmsr)
        {
            nmsr = n;
        }
    }
    /*Output matrix*/
    plhs[0] = mxCreateNumericMatrix(np,nm,mxDOUBLE_CLASS,mxREAL);
    /*Link to the pointer to have access in the code*/
    grav = mxGetPr(plhs[0]);
    for(i=0;i<np;i++)
    {
        for(j=0;j<nm;j++)
        {
            grav[PCMO(np,i,j)] = 0.0;
        }
    }
    /*If we are working with constant density, extract the values to a vector*/
    if(nmsr==1)
    {
        /*Vector creation*/
        rhoc = (double*)malloc(nr*sizeof(double));
        if(rhoc==NULL)
        {
            fprintf(stderr,"Error using malloc() in gpso2d_GravityModels.c\n");
            exit(-1);
        }
        /*Vector filling*/
        for(i=0;i<nr;i++)
        {
            rho = mxGetCell(prhs[2],i);
            rhod = mxGetPr(rho);
            rhoc[i] = rhod[1];
        }
    }
    /*////////////////////////////////////////////////////////////////////////*/
    /*////////////////////////////////////////////////////////////////////////*/
    /*OpenMP parallel*/
#if defined(_OPENMP)
#pragma omp parallel for default(none) \
 shared(nm,nr,nmsr,grav,np,rect,models,points,rhoc,prhs) \
 private(i,j,k,rho,rhod,n,h,l,pos)
#endif
    /*Loop over all models*/
    for(i=0;i<nm;i++)
    {
        /*Loop over all rectangles*/
        for(j=0;j<nr;j++)
        {
            /*Check if we are working with constant or variable density*/
            if(nmsr==1)
            {
                /*Loop over all points*/
                for(k=0;k<np;k++)
                {
                    /*Gravity computation*/
                    grav[PCMO(np,k,i)] += GravityRectangle(rect[PCMO(nr,j,0)],
                                                           rect[PCMO(nr,j,1)],
                                                           models[PCMO(nm,i,j)],
                                                           rect[PCMO(nr,j,2)],
                                                           points[PCMO(np,k,0)],
                                                           points[PCMO(np,k,1)],
                                                           rhoc[j]);
                }
            }
            else
            {
                /*Extract the density definition*/
                rho = mxGetCell(prhs[2],j);
                rhod = mxGetPr(rho);
                n = mxGetM(rho);
                /*Check if there is only one value*/
                if(n==1)
                {
                    /*Loop over all points*/
                    for(k=0;k<np;k++)
                    {
                        /*Gravity computation*/
                        grav[PCMO(np,k,i)] +=
                                          GravityRectangle(rect[PCMO(nr,j,0)],
                                                           rect[PCMO(nr,j,1)],
                                                           models[PCMO(nm,i,j)],
                                                           rect[PCMO(nr,j,2)],
                                                           points[PCMO(np,k,0)],
                                                           points[PCMO(np,k,1)],
                                                           rhod[1]);
                    }
                }
                else
                {
                    /*Loop over all subrectangles*/
                    for(k=0;k<n;k++)
                    {
                        /*Check if the model is deeper*/
                        if(models[PCMO(nm,i,j)]<=rhod[k])
                        {
                            /*Check if it is the first subrectangle*/
                            if(k==0)
                            {
                                /*Top height is the top side of the rectangle*/
                                h = rect[PCMO(nr,j,2)];
                            }
                            else
                            {
                                /*Top height is the previous subrectangle*/
                                h = rhod[PCMO(n,k-1,0)];
                            }
                            /*Loop over all points*/
                            for(l=0;l<np;l++)
                            {
                                /*Gravity computation*/
                                grav[PCMO(np,l,i)] +=
                                          GravityRectangle(rect[PCMO(nr,j,0)],
                                                           rect[PCMO(nr,j,1)],
                                                           rhod[PCMO(n,k,0)],h,
                                                           points[PCMO(np,l,0)],
                                                           points[PCMO(np,l,1)],
                                                           rhod[PCMO(n,k,1)]);
                            }
                        }
                        else
                        {
                            /*Check if it is the first subrectangle*/
                            if(k==0)
                            {
                                /*Top height is the top side of the rectangle*/
                                h = rect[PCMO(nr,j,2)];
                                pos = 0;
                            }
                            else
                            {
                                /*Top height is the las computed bottom height*/
                                h = rhod[PCMO(n,k-1,0)];
                                /*Density is the one referred to the last
                                 *subrectangle, as it defines density upwards */
                                pos = k;
                            }
                            /*Loop over all points*/
                            for(l=0;l<np;l++)
                            {
                                /*Gravity computation*/
                                grav[PCMO(np,l,i)] +=
                                          GravityRectangle(rect[PCMO(nr,j,0)],
                                                           rect[PCMO(nr,j,1)],
                                                           models[PCMO(nm,i,j)],
                                                           h,
                                                           points[PCMO(np,l,0)],
                                                           points[PCMO(np,l,1)],
                                                           rhod[PCMO(n,pos,1)]);
                            }
                            /*No more subrectangles must be used*/
                            break;
                        }
                    }
                }
            }
        }
    } /* --> End of #pragma omp parallel for */
    /*////////////////////////////////////////////////////////////////////////*/
    /*////////////////////////////////////////////////////////////////////////*/
    /*Memory free*/
    if(nmsr==1)
    {
        free(rhoc);
    }
}
/*
Copyright (c) 2023-2025, J.L.G. Pallero, jgpallero@gmail.com,
                         J.L. Fernández Martínez, jlfm@uniovi.es
                         Z. Fernández Muñiz, zulima@uniovi.es
                         Sylvain Bonvalot, sylvain.bonvalot@ird.fr

All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

- Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.
- Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.
- Neither the name of the copyright holders nor the names of its contributors
  may be used to endorse or promote products derived from this software without
  specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL COPYRIGHT HOLDER BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
