/* Computes the gravity generated by a rectangle over anf exterior point */
#include<math.h>
/*Function code*/
double GravityRectangle(double xm,double xM,double zm,double zM,
                        double xp,double zp,double rho)
{
    /*Output*/
    double grav=0.0;
    /*Auxiliary variables*/
    double A=0.0,B=0.0,C=0.0,D=0.0,A2=0.0,B2=0.0,C2=0.0,D2=0.0;
    double p1=0.0,p2=0.0,p3=0.0,p4=0.0;
    /*Gravity constant*/
    /* https://physics.nist.gov/cgi-bin/cuu/Value?bg|search_for=universal_in! */
    double G=6.6743e-11;
    /*////////////////////////////////////////////////////////////////////////*/
    /*////////////////////////////////////////////////////////////////////////*/
    /*Constants for the attraction formula*/
    A = xp-xm;
    B = xp-xM;
    C = zp-zM;
    D = zp-zm;
    /*Squared constants*/
    A2 = A*A;
    B2 = B*B;
    C2 = C*C;
    D2 = D*D;
    /*Formula parts initalization*/
    p1 = 0.0;
    p2 = 0.0;
    p3 = 0.0;
    p4 = 0.0;
    /*The computation is done only if the rectangle dimensions are !=0*/
    if((xm!=xM)&&(zm!=zM))
    {
        /*Computing part 1*/
        if(((A!=0.0)||(C!=0.0))&&((A!=0.0)||(D!=0.0)))
        {
            p1 = A*log((A2+D2)/(A2+C2));
        }
        /*Computing part 2*/
        if(((B!=0.0)||(C!=0.0))&&((B!=0.0)||(D!=0.0)))
        {
            p2 = B*log((B2+D2)/(B2+C2));
        }
        /*Computing part 3*/
        if(D!=0.0)
        {
            p3 = 2.0*D*(atan(A/D)-atan(B/D));
        }
        /*Computing part 4*/
        if(C!=0.0)
        {
            p4 = 2.0*C*(atan(A/C)-atan(B/C));
        }
    }
    /*Apply rho and G*/
    grav = G*rho*(p1-p2+p3-p4);
    /*////////////////////////////////////////////////////////////////////////*/
    /*////////////////////////////////////////////////////////////////////////*/
    /*End of function*/
    return grav;
}
/*
Copyright (c) 2023, J.L.G. Pallero, jgpallero@gmail.com,
                    J.L. Fernández Martínez, jlfm@uniovi.es
                    Z. Fernández Muñiz, zulima@uniovi.es
                    Sylvain Bonvalot, sylvain.bonvalot@ird.fr

All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

- Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.
- Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.
- Neither the name of the copyright holders nor the names of its contributors
  may be used to endorse or promote products derived from this software without
  specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL COPYRIGHT HOLDER BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
