function GUIcloseRequest

%--------------------------------------------------------------------------
%GRAPHICAL INTERFACE
%--------------------------------------------------------------------------

%Size of the current window
width = 350;
height = 150;
%Centralize the current window at the center of the screen
[posX,posY,Width,Height]=centralizeWindow(width,height);
figposition = [posX,posY,Width,Height];

GUIcloseRequest_ = figure('Name','Close Program?',...
    'Visible','off',...
    'NumberTitle','off',...
    'Units','pixel',...
    'position',figposition,...
    'Toolbar','none',...
    'MenuBar','none',...
    'Resize','off',...
    'Tag','closeRequest',...
    'WindowStyle','normal',...
    'CloseRequestFcn',@selection_callBack);

uicontrol(GUIcloseRequest_,'Style','pushbutton',...
    'units','normalized',...
    'Selected','on',...
    'String','Just the main GUI',...
    'fontUnits','normalized',...
    'position',[0.05 0.6 0.9 0.18],...
    'CallBack',@selection_callBack);

uicontrol(GUIcloseRequest_,'Style','pushbutton',...
    'units','normalized',...
    'String','Both the main and complementary GUI''s',...
    'fontUnits','normalized',...
    'position',[0.05 0.34 0.9 0.18],...
    'CallBack',@selection_callBack);

uicontrol(GUIcloseRequest_,'Style','pushbutton',...
    'units','normalized',...
    'String','No',...
    'fontUnits','normalized',...
    'position',[0.05 0.08 0.9 0.18],...
    'CallBack',@selection_callBack);

set(GUIcloseRequest_,'Visible','on')
%--------------------------------------------------------------------------
%CALLBACKS
%--------------------------------------------------------------------------

function selection_callBack(hObject,varargin)
%Retrieve the handle structure
handles = guidata(GUIcloseRequest_);

if(strcmp(get(hObject,'Tag'),'closeRequest'))
    set(GUIcloseRequest_,'Visible','off')
    choice = 3;
elseif(strcmp(get(hObject,'String'),'Just the main GUI'))
    set(GUIcloseRequest_,'Visible','off')
    choice = 1;
elseif(strcmp(get(hObject,'String'),'Both the main and complementary GUI''s'))
    set(GUIcloseRequest_,'Visible','off')
    choice = 2;
else
    set(GUIcloseRequest_,'Visible','off')
    choice = 3;
end

handles.choice = choice;
%Update de handle structure
guidata(GUIcloseRequest_,handles);
end

end