function GUIdikeLikeBody

%--------------------------------------------------------------------------
%GRAPHICAL INTERFACE
%--------------------------------------------------------------------------

%Size of the current window
width = 1360;
height = 768;
%Centralize the current window at the center of the screen
[posX,posY,Width,Height]=centralizeWindow(width,height);
figposition = [posX,posY,Width,Height];

GUIdikeLikeBody_ = figure('Name','Dyke-Like Body Forward Modeling',...
    'Visible','off',...
    'NumberTitle','off',...
    'Units','pixel',...
    'position',figposition,...
    'Toolbar','figure',...
    'MenuBar','none',...
    'Resize','off',...
    'Tag','GMS',...
    'WindowStyle','normal');

%--------------------------------------------------------------------------

parameters = uipanel(GUIdikeLikeBody_,...
    'Units','normalized',...
    'position',[0.014 0.02 0.2 0.96]);

MinX = uicontrol(parameters,'Style','edit',...
    'TooltipString','Minimum value of the horizontal extent.',...
    'units','normalized',...
    'String','0',...
    'fontUnits','normalized',...
    'position',[0.03 0.93 0.944 0.036]);

MaxX = uicontrol(parameters,'Style','edit',...
    'TooltipString','Maximum value of the horizontal extent.',...
    'units','normalized',...
    'String','1000',...
    'fontUnits','normalized',...
    'position',[0.03 0.88 0.944 0.036]);

Station = uicontrol(parameters,'Style','edit',...
    'TooltipString','Number of stations.',...
    'units','normalized',...
    'String','500',...
    'fontUnits','normalized',...
    'position',[0.03 0.83 0.944 0.036]);

CoordX = uicontrol(parameters,'Style','edit',...
    'TooltipString','Horizontal coordinate of the dyke.',...
    'units','normalized',...
    'String','500',...
    'fontUnits','normalized',...
    'position',[0.03 0.78 0.944 0.036]);

CoordZ = uicontrol(parameters,'Style','edit',...
    'TooltipString','Depth of the dyke.',...
    'units','normalized',...
    'String','20',...
    'fontUnits','normalized',...
    'position',[0.03 0.73 0.944 0.036]);

S = uicontrol(parameters,'Style','edit',...
    'TooltipString','Dip.',...
    'units','normalized',...
    'String','90',...
    'fontUnits','normalized',...
    'position',[0.03 0.68 0.944 0.036]);

W = uicontrol(parameters,'Style','edit',...
    'TooltipString','Width.',...
    'units','normalized',...
    'String','30',...
    'fontUnits','normalized',...
    'position',[0.03 0.63 0.944 0.036]);

T = uicontrol(parameters,'Style','edit',...
    'TooltipString','Stregth of geomagnetic field.',...
    'units','normalized',...
    'String','23000',...
    'fontUnits','normalized',...
    'position',[0.03 0.58 0.944 0.036]);

I_e = uicontrol(parameters,'Style','edit',...
    'TooltipString','Field inclination.',...
    'units','normalized',...
    'String','90',...
    'fontUnits','normalized',...
    'position',[0.03 0.53 0.944 0.036]);

D_e = uicontrol(parameters,'Style','edit',...
    'TooltipString','Field declination.',...
    'units','normalized',...
    'String','0',...
    'fontUnits','normalized',...
    'position',[0.03 0.48 0.944 0.036]);

Dens_ = uicontrol(parameters,'Style','edit',...
    'TooltipString','Density contrast.',...
    'units','normalized',...
    'String','500',...
    'fontUnits','normalized',...
    'position',[0.03 0.43 0.944 0.036]);

k = uicontrol(parameters,'Style','edit',...
    'TooltipString','Susceptibility contrast.',...
    'units','normalized',...
    'String','0.027',...
    'fontUnits','normalized',...
    'position',[0.03 0.38 0.944 0.036]);

rdb_Reman = uicontrol(parameters,'Style','radiobutton',...
    'units','normalized',...
    'Value',0,...
    'String','Add Remanent Magnetization?',...
    'fontUnits','normalized',...
    'position',[0.03 0.33 0.944 0.036],...
    'Callback',@allowRemanentMag_callBack);

R = uicontrol(parameters,'Style','edit',...
    'TooltipString','Remanent intensity.',...
    'units','normalized',...
    'String','0',...
    'fontUnits','normalized',...
    'Enable','off',...
    'position',[0.03 0.28 0.25 0.036]);

I_r = uicontrol(parameters,'Style','edit',...
    'TooltipString','Remanent inclination.',...
    'units','normalized',...
    'String','0',...
    'fontUnits','normalized',...
    'Enable','off',...
    'position',[0.375 0.28 0.25 0.036]);

D_r = uicontrol(parameters,'Style','edit',...
    'TooltipString','Remanent declination.',...
    'units','normalized',...
    'String','0',...
    'fontUnits','normalized',...
    'Enable','off',...
    'position',[0.72 0.28 0.25 0.036]);

uicontrol(parameters,'Style','pushbutton',...
    'units','normalized',...
    'String','Calculate the Magnetic Anomaly',...
    'fontUnits','normalized',...
    'position',[0.03 0.23 0.944 0.036],...
    'CallBack',@MagAnom_callBack);

%--------------------------------------------------------------------------
graphPanel = uipanel(GUIdikeLikeBody_,...
    'Units','normalized',...
    'BackgroundColor','white',...
    'position',[0.23 0.02 0.76 0.96]);

graphAnomaly = axes(graphPanel,...
    'Units','normalized',...
    'position',[0.07 0.55 0.88 0.4]);
set(graphAnomaly.XAxis,'Visible','off');
set(graphAnomaly.YAxis,'Visible','off');

graphSources = axes(graphPanel,...
    'Units','normalized',...
    'position',[0.07 0.1 0.88 0.35]);
set(graphSources.XAxis,'Visible','off');
set(graphSources.YAxis,'Visible','off');

%--------------------------------------------------------------------------
%MENU
%--------------------------------------------------------------------------

file = uimenu(GUIdikeLikeBody_,'label','File');

uimenu(file,'Label','Save Anomaly...','Accelerator','S','CallBack',@saveFile_callBack);

anomalyGenerated = 'n';
set(GUIdikeLikeBody_,'Visible','on')
%--------------------------------------------------------------------------
%CALLBACKS
%--------------------------------------------------------------------------

%ALLOW REMANENT MAGNETIZATION
function allowRemanentMag_callBack(hObject,callbackdata,handles)
%Retrieve the handle structure
handles = guidata(hObject);

if(rdb_Reman.Value==1)
    R.Enable = 'on';
    I_r.Enable = 'on';
    D_r.Enable = 'on';
else
    R.Enable = 'off';
    I_r.Enable = 'off';
    D_r.Enable = 'off';
end

%Update de handle structure
guidata(hObject,handles);
end

%CALCULATE THE MAGNETIC ANOMALY OF THE DYKE
function MagAnom_callBack(hObject,callbackdata,handles)
%Retrieve the handle structure
handles = guidata(hObject);

x0 = str2double(get(MinX,'String'));
xf = str2double(get(MaxX,'String'));
stations = str2double(get(Station,'String'));
DimX = linspace(x0,xf,stations);
coordX = str2double(get(CoordX,'String'));
H = str2double(get(CoordZ,'String'));
S_ = degtorad(str2double(get(S,'String')));
W_ = str2double(get(W,'String'));
T_ = str2double(get(T,'String'));
T_ = (T_*(10^(7)))/(4*pi*(10^(10)));
Ie = degtorad(str2double(get(I_e,'String')));
De = degtorad(str2double(get(D_e,'String')));
d = str2double(get(Dens_,'String'));
k_ = str2double(get(k,'String'));

I_e_ = atan(tan(Ie)/cos(De));

B = W_/2;
E_ = k_*T_;

if(get(rdb_Reman,'Value')==1)
    R_ = str2double(R.String);
    R_ = R_*E_;
    Ir = degtorad(str2double(I_r.String));
    Dr = degtorad(str2double(D_r.String));
    I_r_ = atan(tan(Ir)/cos(Dr));
else
    E_ = 2*E_;
    R_ = 0;
    Ir = Ie;
    Dr = De;
end

%RESULTANTE
comp_i_cos = E_*cos(Ie)+R_*cos(Ir);
comp_i_sin = E_*sin(Ie)+R_*sin(Ir);
comp_d_cos = E_*cos(De)+R_*cos(Dr);
comp_d_sin = E_*sin(De)+R_*sin(Dr);
i_j = atan(comp_i_sin/comp_i_cos);
d_j = atan(comp_d_sin/comp_d_cos);
I_j_ = atan(tan(i_j)/cos(d_j));

%DISTÂNCIAS
X = zeros(1,length(DimX));
for x_=1:length(DimX)
    X(x_) = (DimX(x_)-coordX);
end

%EFFECTIVE INCLINATION
theta = I_e_ + I_j_ - S_ - degtorad(90);

%AMPLITUDE FACTOR
A = 2*k_*T_*sin(S_)*sqrt(1-cos(Ie)^2*sin(De)^2);

%MAGNETIC ANOMALY
delta_T = 10^3.*A.*(cos(theta)*(atan((X+B)./H)-atan((X-B)./H))+(1/2).*sin(theta).*log(((X+B).^2+H.^2)./((X-B).^2+H.^2)));

S_ = rad2deg(S_);
if(S_==90)
    dike_type = 'Vertical Dyke';
elseif(S_==0 || S_==180)
    dike_type = 'Horizontal Dyke';
else
    dike_type = 'Oblique Dyke';
end

axes(graphAnomaly)
plot(DimX,delta_T,'k','LineWidth',1.5)
xlabel('Profile Direction')
ylabel('Magnetic Anomaly [nT]')
title(dike_type)
set(gca,'FontSize',12)

axes(graphSources)
Rp = [coordX -H 0]; %Point about which to rotate.

%Vertices of the dyke
coord_x = [(coordX-W_/2),(coordX+W_/2),(coordX+W_/2),(coordX-W_/2)];
coord_y = [-H,-H,-1000*H,-1000*H];

plot([min(DimX) max(DimX)],[0 0],'k')
xlabel('Profile Direction')
ylabel('Depth [m]')
hold on
L2 = fill(coord_x,coord_y,[.5 .5 .5]);
hold off
axis tight
J = (308*max(DimX))/952;
axis([min(DimX) max(DimX) -J 0])
set(gca,'FontSize',12)

P = [0,0,1];

angle = S_-90;
rotate(L2,P,-angle,Rp)

handles.delta_T = delta_T;
handles.DimX = DimX;
anomalyGenerated = 'y';
%Update de handle structure
guidata(hObject,handles);
end

%SET THE OUTPUT DATASET PATH AND SAVE
function saveFile_callBack(hObject,callbackdata,handles)
%Retrieve the handle structure
handles = guidata(hObject);

if(anomalyGenerated=='y')
    DimX = handles.DimX;
    DimX = DimX';
    inputFile = handles.delta_T;
    inputFile = inputFile';
    
    outputFile = cat(2,DimX,inputFile);
    
    [FileName,PathName] = uiputfile({'*.xyz;*.txt;*.dat','Data Files (*.xyz,*.txt,*.dat)'},'Save File...');
    Fullpath = [PathName FileName];
    if (Fullpath == 0)
        return;
    end
    
    outputFile_path.String=num2str(Fullpath);
    
    fid = fopen(Fullpath,'w+');
    fprintf(fid,'%8s %8s\r\n','X','Dique_mag');
    fprintf(fid,'%6.2f %12.8e\r\n',transpose(outputFile));
    fclose(fid);
else
    msgbox('Generate the magnetic anomaly before trying to save the output file.','Warn','warn')
    return
end

%Update de handle structure
guidata(hObject,handles);
end

end