function GUIbodyParameters

%Size of the current window
width = 300;
height = 200;
%Centralize the current window at the center of the screen
[posX,posY,Width,Height]=centralizeWindow(width,height);
figposition = [posX,posY,Width,Height];

GUIbodyParameters_ = figure('Menubar','none',...
    'Name','Body Parameters',...
    'NumberTitle','off',...
    'NextPlot','add',...
    'units','pixel',...
    'position',figposition,...
    'Toolbar','none',...
    'Visible','off',...
    'Resize','off',...
    'WindowStyle','modal',...
    'Tag','bodyParameters',...
    'CloseRequestFcn',@doneBodyParam_callBack);

suscept = uicontrol(GUIbodyParameters_,...
    'TooltipString','Susceptibility contrast.',...
    'Style','edit',...
    'units','normalized',...
    'String','0.0276',...
    'fontUnits','normalized',...
    'position',[0.1 0.75 0.8 0.125]);

dens = uicontrol(GUIbodyParameters_,...
    'TooltipString','Density contrast [kg/cm^3].',...
    'Style','edit',...
    'units','normalized',...
    'String','2500',...
    'fontUnits','normalized',...
    'position',[0.1 0.6 0.8 0.125]);

I_ = uicontrol(GUIbodyParameters_,'Style','edit',...
    'TooltipString','Magnetic field inclination [degrees].',...
    'units','normalized',...
    'String','90',...
    'fontUnits','normalized',...
    'position',[0.1 0.45 0.8 0.125]);

strike_ = uicontrol(GUIbodyParameters_,'Style','edit',...
    'TooltipString','Angle between magnetic north and strike of the body [degrees].',...
    'units','normalized',...
    'String','90',...
    'fontUnits','normalized',...
    'position',[0.1 0.3 0.8 0.125]);

uicontrol(GUIbodyParameters_,'Style','pushbutton',...
    'units','normalized',...
    'String','Done',...
    'fontUnits','normalized',...
    'position',[0.1 0.15 0.8 0.125],...
    'CallBack',@doneBodyParam_callBack);

set(GUIbodyParameters_,'Visible','on')
%--------------------------------------------------------------------------
%CALLBACK FUNCTIONS
%--------------------------------------------------------------------------

%SET THE BODY PARAMETERS
function doneBodyParam_callBack(varargin)
%Retrieve the handle structure
handles = guidata(GUIbodyParameters_);

handles.suscept = str2double(get(suscept,'String'));
handles.dens = str2double(get(dens,'String'));
handles.I_ = str2double(get(I_,'String'));
handles.strike_ = str2double(get(strike_,'String'));

set(GUIbodyParameters_,'Visible','off')

%Update de handle structure
guidata(GUIbodyParameters_,handles);
end

end