function GUIwsParameters

%Size of the current window
width = 300;
height = 350;
%Centralize the current window at the center of the screen
[posX,posY,Width,Height]=centralizeWindow(width,height);
figposition = [posX,posY,Width,Height];

GUIwsParameters_ = figure('Menubar','none',...
    'Name','Workspace Parameters',...
    'NumberTitle','off',...
    'NextPlot','add',...
    'units','pixel',...
    'position',figposition,...
    'Toolbar','none',...
    'Visible','off',...
    'Resize','off',...
    'Tag','WSparameters',...
    'WindowStyle','modal',...
    'CloseRequestFcn',@doneWorkspace_callBack);

minX = uicontrol(GUIwsParameters_,...
    'TooltipString','Left border limit of the model (meters).',...
    'Style','edit',...
    'units','normalized',...
    'String','-500',...
    'fontUnits','normalized',...
    'position',[0.1 0.87 0.8 0.075],...
    'CallBack',@minX_callBack);

maxX = uicontrol(GUIwsParameters_,...
    'TooltipString','Right border limit of the model (meters).',...
    'Style','edit',...
    'units','normalized',...
    'String','500',...
    'fontUnits','normalized',...
    'position',[0.1 0.77 0.8 0.075],...
    'CallBack',@maxX_callBack);

minY = uicontrol(GUIwsParameters_,...
    'TooltipString','Minimum depth value (meters).',...
    'Style','edit',...
    'units','normalized',...
    'String','0',...
    'fontUnits','normalized',...
    'position',[0.1 0.67 0.8 0.075]);

maxY = uicontrol(GUIwsParameters_,...
    'TooltipString','Maximum depth value (meters).',...
    'Style','edit',...
    'units','normalized',...
    'String','1000',...
    'fontUnits','normalized',...
    'position',[0.1 0.57 0.8 0.075]);

bFactor = uicontrol(GUIwsParameters_,...
    'TooltipString','Percent factor that controls the actual border limits.',...
    'Style','edit',...
    'units','normalized',...
    'String','80',...
    'fontUnits','normalized',...
    'position',[0.1 0.42 0.8 0.075],...
    'CallBack',@bFactor_callBack);

borderMinX = uicontrol(GUIwsParameters_,...
    'TooltipString','Actual left border limit (meters).',...
    'Style','edit',...
    'units','normalized',...
    'String','0',...
    'fontUnits','normalized',...
    'position',[0.1 0.27 0.38 0.075]);

borderMaxX = uicontrol(GUIwsParameters_,...
    'TooltipString','Actual right border limit (meters).',...
    'Style','edit',...
    'units','normalized',...
    'String','0',...
    'fontUnits','normalized',...
    'position',[0.52 0.27 0.38 0.075]);

stations = uicontrol(GUIwsParameters_,...
    'TooltipString','Number of stations (measuring points).',...
    'Style','edit',...
    'units','normalized',...
    'String','200',...
    'fontUnits','normalized',...
    'position',[0.1 0.17 0.8 0.075]);

uicontrol(GUIwsParameters_,...
    'Style','pushbutton',...
    'units','normalized',...
    'String','Done',...
    'fontUnits','normalized',...
    'position',[0.1 0.07 0.8 0.075],...
    'CallBack',@doneWorkspace_callBack);

set(borderMinX,'String',num2str(str2double(get(minX,'String'))-(str2double(get(maxX,'String'))-str2double(get(minX,'String')))*0.8))
set(borderMaxX,'String',num2str(str2double(get(maxX,'String'))+(str2double(get(maxX,'String'))-str2double(get(minX,'String')))*0.8))

set(GUIwsParameters_,'Visible','on')
%--------------------------------------------------------------------------
%CALLBACK FUNCTIONS
%--------------------------------------------------------------------------

%SET MIN X
function minX_callBack(varargin)
%Retrieve the handle structure
handles = guidata(GUIwsParameters_);

mX = str2double(get(minX,'String'));
pX = str2double(get(maxX,'String'));
factor = str2double(get(bFactor,'String'))/100;

set(borderMinX,'String',num2str(mX-(pX-mX)*factor))
set(borderMaxX,'String',num2str(pX+(pX-mX)*factor))

%Update de handle structure
guidata(GUIwsParameters_,handles);
end

%SET MAX X
function maxX_callBack(varargin)
%Retrieve the handle structure
handles = guidata(GUIwsParameters_);

mX = str2double(get(minX,'String'));
pX = str2double(get(maxX,'String'));
factor = str2double(get(bFactor,'String'))/100;

set(borderMinX,'String',num2str(mX-(pX-mX)*factor))
set(borderMaxX,'String',num2str(pX+(pX-mX)*factor))

%Update de handle structure
guidata(GUIwsParameters_,handles);
end

%SET BORDER FACTOR
function bFactor_callBack(varargin)
%Retrieve the handle structure
handles = guidata(GUIwsParameters_);

mX = str2double(get(minX,'String'));
pX = str2double(get(maxX,'String'));
factor = str2double(get(bFactor,'String'))/100;

set(borderMinX,'String',num2str(mX-(pX-mX)*factor))
set(borderMaxX,'String',num2str(pX+(pX-mX)*factor))

%Update de handle structure
guidata(GUIwsParameters_,handles);
end

%DONE SETTING WORKSPACE
function doneWorkspace_callBack(varargin)
%Retrieve the handle structure
handles = guidata(GUIwsParameters_);

handles.minX = str2double(get(minX,'String'));
handles.maxX = str2double(get(maxX,'String'));
handles.minY = str2double(get(minY,'String'));
handles.maxY = str2double(get(maxY,'String'));
handles.bFactor = str2double(get(bFactor,'String'));
handles.borderMinX = str2double(get(borderMinX,'String'));
handles.borderMaxX = str2double(get(borderMaxX,'String'));
handles.stations = str2double(get(stations,'String'));

set(GUIwsParameters_,'Visible','off')

%Update de handle structure
guidata(GUIwsParameters_,handles);
end

%--------------------------------------------------------------------------
%LOCAL FUNCTIONS
%--------------------------------------------------------------------------



end